###查询课程基本信息
POST http://{{gateway_host}}/content/course/list?pageNo=1&pageSize=2
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ6aGFuZ3NhbiIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2ODUxMTA0ODYsImF1dGhvcml0aWVzIjpbInAxIl0sImp0aSI6IjQwNzQyZWNmLTQ4YzUtNDkyMS05ZDIxLTZhMTZjZWE0YjM5MiIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.KAoue2VskpUtznRNXHhkRvsViqckalA8Newr360LSU8
Content-Type: application/json

{
  "auditStatus": "",
  "courseName": "java",
  "publishStatus": ""
}

### 查询课程分类
GET http://{{content_host}}/content/course-category/tree-nodes

### 创建课程
POST http://{{content_host}}/content/course
Content-Type: application/json

{
  "mt": "1-1",
  "st": "1-1-1",
  "name": "",
  "pic": "wdaddfawads",
  "teachmode": "200002",
  "users": "初级人员",
  "tags": "tagstagstags",
  "grade": "204001",
  "description": "12345",
  "charge": "201001",
  "price": 10,
  "originalPrice": 100,
  "qq": "214312232",
  "wechat": "1234243",
  "phone": "1332432424",
  "validDays": 365
}

###根据课程id查询课程信息
GET http://{{content_host}}/content/course/40
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ7XCJjb21wYW55SWRcIjpcIjEyMzIxNDE0MjVcIixcImNyZWF0ZVRpbWVcIjpcIjIwMjItMDktMjhUMDg6MzI6MDNcIixcImlkXCI6XCI1MlwiLFwibmFtZVwiOlwiTeiAgeW4iFwiLFwic2V4XCI6XCIxXCIsXCJzdGF0dXNcIjpcIlwiLFwidXNlcm5hbWVcIjpcInQxXCIsXCJ1dHlwZVwiOlwiMTAxMDAyXCJ9Iiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTY4NTE3Njc5MSwiYXV0aG9yaXRpZXMiOlsidGVzdCJdLCJqdGkiOiIwOWQ2ZmI0Zi1mZTUwLTQ1NjYtYjY4Yy0yN2NmYTQ2NmQxZmYiLCJjbGllbnRfaWQiOiJYY1dlYkFwcCJ9.iESWlYypbsC0dKwbXtO5n0zUEP5W2s2Pe5-KMzIbT5w
Content-Type: application/json

###根据课程id查询课程计划
GET http://{{gateway_host}}/content/teachplan/117/tree-nodes
Content-Type: application/json

### 删除课程计划
DELETE http://{{content_host}}/content/teachplan/292
Content-Type: application/json

### 查询教师
GET http://{{content_host}}/content/courseTeacher/list/75
Content-Type: application/json

###新增教师
POST http://{{content_host}}/content/courseTeacher
Content-Type: application/json

{
  "courseId": 75,
  "teacherName": "王老师",
  "position": "教师职位",
  "introduction": "教师简介"
}

###修改教师
POST http://{{content_host}}/content/courseTeacher
Content-Type: application/json

{
  "id": 24,
  "courseId": 75,
  "teacherName": "王老师王老师",
  "position": "教师职位教师职位",
  "introduction": "教师简介教师简介",
  "photograph": null,
  "createDate": null
}

###删除教师
DELETE http://{{content_host}}/content/ourseTeacher/course/75/23